services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
      MYSQL_DATABASE: airdnb
      MYSQL_USER: gromit
      MYSQL_PASSWORD: pwd1234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  airdnb-local-prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  airdnb-local-grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

volumes:
  mysql_data: