spring:
  profiles:
    default: local, email, paymentKey

server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        same-site: strict
        http-only: true
        secure: true