spring:
  profiles:
    default: local, email, paymentKey

server:
  tomcat: # tomcat metric
    mbeanregistry:
      enabled: true
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        same-site: strict
        http-only: true
        secure: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9292