spring:
  profiles:
    default: local, email, paymentKey

server:
  tomcat: # tomcat metric
    mbeanregistry:
      enabled: true
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        same-site: strict
        http-only: true
        secure: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
  server:
    port: 9292

resilience4j:
  circuitbreaker:
    failure-rate-threshold: 10   # 실패 10% 이상 시 서킷 오픈, slowCallRateThreshold와 같다.
    slow-call-duration-threshold: 30000   # 30000ms(30초) 이상 소요 시 실패로 간주
    slow-call-rate-threshold: 10   # slowCallDurationThreshold 초과 비율이 10% 이상 시 서킷 오픈
    wait-duration-in-open-state: 30000   # OPEN -> HALF-OPEN 전환 전 기다리는 시간을 30초로 지정
    minimum-number-of-calls: 50   # failureRate, slowCallRate 집계에 필요한 최소 호출 수
    sliding-window-size: 100   # 서킷 CLOSE 상태에서 N회 호출 도달 시 failureRateThreshold 실패 비율 계산
    permitted-number-of-calls-in-half-open-state: 30   # HALF_OPEN -> CLOSE or OPEN 으로 판단하기 위해 호출 횟수