spring:
  config:
    import: classpath:/config/application-paymentKey.yml, classpath:/config/application-email.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/airbnb_test
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

logging.level:
  org.hibernate.SQL: debug