spring:
  config:
    import: classpath:application-secret.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/airbnb_test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

logging.level:
  org.hibernate.SQL: debug