### 결제 임시 데이터 저장 API (호출 전에 login.http 실행)
POST localhost:8080/payment/reservation/1/request?paymentKey=tviva20241021175818asZ71&amount=50000&orderId=MC4wNzQ5OTc3MTE3NDc2
Content-Type: application/json

### 결제 임시 데이터 저장 API (login.http, 결제 임시 데이터 저장 API 호출 후 사용)
POST localhost:8080/payment/1/confirm
Content-Type: application/json

{
  "reservationId": 1,
  "paymentKey": "tviva20241021175818asZ71",
  "amount": "50000",
  "orderId": "MC4wNzQ5OTc3MTE3NDc2"
}