POST localhost:8080/stay
Content-Type: application/json

{
  "memberId": "1",
  "title": "제목2",
  "description": "설명2",
  "checkInTime": "01:01",
  "checkOutTime": "12:00",
  "feePerNight" : "50000",
  "guestCount" :"1",
  "longitude" : 104.5,
  "latitude" : 46.5,
  "images" : ["1", "2", "#", "4", "5"]
}

###
GET localhost:8080/stay/1

###
PUT localhost:8080/stay/1/image
Content-Type: application/json

[
    "changeURL1",
    "changeURL2",
    "changeURL3",
    "changeURL4",
    "changeURL5",
    "changeURL6"
]

### 숙소의 예약된 날짜 조회 API
GET localhost:8080/stay/1/reservedDates
Content-Type: application/json

