spring:
  application:
    name: be

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/airbnb
    username: team04
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 465
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true     # SMTP 서버의 인증 여부
          starttls:
            enable: true # SMTP 통신을 TLS로 암호화하여 통신
          ssl:
            trust: smtp.naver.com  # SSL을 사용해서 SMTP서버 신뢰
            enable: true  # SMTP통신이 SSL로 암호화
        debug: true


logging:
  level:
    airdnb: debug