name: Docker 기반 CI/CD 구축

on:
  push:
    branches:
      - feat/#31

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repo 에서 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 테스트 & 빌드
        run : |
          chmod +x ./gradlew
          ./gradlew clean build
