name: 테스트 CI

on:
  push:
    branches:
      - feat/#49

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repo 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle 명령 실행을 위한 권한 부여
        run: chmod +x gradlew

      - name: Gradle build 수행
        run: ./gradlew test
