name: CI 테스트 자동화

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feat/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repo 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle 명령 실행을 위한 권한 부여
        run: chmod +x gradlew

      - name: Gradle build 수행
        run: |
          echo "${{ secrets.APPLICATION_SECRET_PROPERTIES }}" > ./src/main/resources/application-secret.yml
          ./gradlew test

